version: "3"
services:
  api:
    build: RapidFarmApi/
    ports: 
      - "8000:80"
      - "8001:443"
    env_file: ".env"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - db
    command: ["dotnet", "ef", "database update"]

  db:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"