version: "3"

networks:
  dev:
    driver: bridge

services:
  api:
    build: RapidFarmApi/
    ports: 
      - "8000:80"
      - "8001:443"
    env_file: ".env"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres
    env_file: ".env"
    networks:
      - dev
    ports:
      - "5432:5432"

